### PR TITLE
Add component origami type as an alternative name for origami type module

### PR DESCRIPTION
**Pull request by JakeChampion**

### CODE REVIEW

**Comment by chee** [comment]
i don't think we've done the other prerequisite work for this yet, have we?

**Comment by JakeChampion** [comment]
I think this was the only piece of work we needed to do? -- https://github.com/Financial-Times/origami-repo-data/pull/139

Is there something else we need to do?

**Comment by JakeChampion** [comment]
@chee do you know what the other pieces of work are we need to do first?

**Comment by chee** [comment]
oh:) yes that was the work i was thinking of!

**Comment by chee** [comment]
g2g!

**Pull request merged**
