### PR TITLE
Clarify that letter means ASCII letter

### PR DESCRIPTION
**Pull request by JakeChampion**
Conversation about this was in our Slack channel -- https://financialtimes.slack.com/archives/CSW6B2VAN/p1590060554038100

### CODE REVIEW

**Comment by chee** [comment]
:D

**Comment by chee** [comment]
should we clarify that by hyphen we mean ascii character 0x2D and not unicode character U+2010? jk

**Comment by chee** [comment]
is it normal to know what ASCII letter means?

**Comment by JakeChampion** [comment]
> is it normal to know what ASCII letter means?

I think it is, but we could either explain it inline or via the `<abbr>` element or a link?

**Pull request merged**
