### PR TITLE
Add mission and vision statements to the homepage

### PR DESCRIPTION
**Pull request by JakeChampion**
Closes https://github.com/Financial-Times/origami-website/issues/292

### CODE REVIEW

**Comment by notlee** [comment]
I think as someone new to Origami I'd find this quite confusing. Without context the vision/mission statements don't really say what Origami is.

What do we think to introducing Origami a little more gently with "Origami is a group of services, components, and tools used to help build digital products for FT brands."

And having a separate area for mission and vision statements? 

Because we're talking about Origami the project not Origami the team, we need to tweak some other areas too. One that jumps out is under "Contact Us", "We're here to help." would probably be better as "The Origami team are here to help."

**Comment by JakeChampion** [comment]
> I think as someone new to Origami I'd find this quite confusing. Without context the vision/mission statements don't really say what Origami is.
> 
> What do we think to introducing Origami a little more gently with "Origami is a group of services, components, and tools used to help build digital products for FT brands."
> 
> And having a separate area for mission and vision statements?
> 
> Because we're talking about Origami the project not Origami the team, we need to tweak some other areas too. One that jumps out is under "Contact Us", "We're here to help." would probably be better as "The Origami team are here to help."

These are great suggestions 👍

**Comment by JakeChampion** [comment]
[New homepage](https://ft-origami-origami-s-mi-xddbx5.herokuapp.com/) copy, I removed a column/card of text and rewrote the contact text:
image

I added a new page under the [Principles section](https://ft-origami-origami-s-mi-xddbx5.herokuapp.com/docs/principles/#vision-and-mission-statements) for the vision and mission statements:
image

[Here is the new page](https://ft-origami-origami-s-mi-xddbx5.herokuapp.com/docs/principles/vision-and-mission/) I added for the vision and mission statements:
image

**Comment by JakeChampion** [comment]
@notlee what do you think of the new version? :-)

**Comment by notlee** [comment]
That's great @JakeChampion! The rewording of the contact section is nice "a community Slack channel" 👍  And good idea to put the mission/vision page under principles.

I'd be good to link to those from the homepage. I didn't feel they fit well before on the homepage but do want us to shout about them! Maybe we could introduce an "About" section where "Origami Team" used to be? 

>About
>
>Origami is a collaborative project by and for the FT which includes services, components, and tools used to help design & build digital products for FT brands.
>
> [Origami Project Mission & Vision Statements](#)

Let's also add "design" to the intro?
```diff
- [...] help build digital products for FT brands.
+ [...] help design & build digital products for FT brands.
```

**Comment by JakeChampion** [comment]
@notlee Here is the updated homepage :-)

image

**Review by notlee — APPROVED** [review]
Looks good to me!

**Comment by JakeChampion** [comment]
@chee What do you think of this? Happy for it to be merged?

**Review by chee — APPROVED** [review]

**Pull request merged**
